### ISSUE TITLE
Player reach conflict

### ISSUE THREAD

**Issue by VortiK** [Suprcheese/Map-Ping#1]
Hello, 

I'm using this mod and found a problem with another mod that changes the player reach distance (creativemod, armor reach and probably others).

I saw in your mod that you change player build range when using the map ping tool and then reset the player build distance to 0.

This should instad be reset to whatever the value was before you changed it, other with any other mod changing the build distance won't work.

https://github.com/Suprcheese/Map-Ping/blob/master/control.lua#L88

Regards

**Comment by Suprcheese** [comment]
Fxed in r26: https://github.com/Suprcheese/Map-Ping/commit/44011d64353e31a670548c7a1cf4eb03d5587e8d
